[versions]
hilt = "2.44"
compose-bom = "2023.03.00"
activity-compose = "1.8.1"
firebase-bom = "32.6.0"

[libraries]
# Compose
composeBom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui = { group = "androidx.compose.ui", name = "ui" }
uiGraphics = { group = "androidx.compose.ui", name = "ui-graphics" }
uiTooling = { group = "androidx.compose.ui", name = "ui-tooling" }
uiToolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
uiTestManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
material3 = { group = "androidx.compose.material3", name = "material3" }
activityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }

# Hilt
daggerHilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
daggerHiltCompiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

# Firebase
firebaseBom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebaseAnalytics= { group = "com.google.firebase", name = "firebase-analytics" }

[plugins]
